### PR TITLE
KSM recovery mode

### PR DESCRIPTION
**Pull request by jleni**
separate S and X build workflows

### CODE REVIEW

**Comment by feelwelltm** [comment]
in the ledger today was an update with kusama,I have made the update in my ledger but the same error 1010....offffff

**Comment by gorgos** [comment]
> in the ledger today was an update with kusama,I have made the update in my ledger but the same error 1010....offffff

I don't know, but it's possible you have to get the second version of the app here:

image

**Comment by daledenton1** [comment]
I only had the one update, still doesn't work

**Comment by feelwelltm** [comment]
I have reinstalled the new kusama version 4.28.2  on my nano ledger s.
I have the same 1010 error with my ledger when i want to transfer the Kusama from the Polkadot wallet!  on the  https://polkadot.js.org/apps 
i cant send the kusama anywhere!!!!! please help and make a version of Kusama that works!!! I have ledger for security not for problems ok...be serious

when the Kusama App - DOT recovery mode will be released for us, so we can move the Kusama from Polkadot wallet...when??? there are real money blocked in  https://polkadot.js.org

**Comment by elfif** [comment]
Hello there. 
I successfully installed the kusama_sec app.
@feelwelltm @daledenton1 , you need to enable "Developer mode" in settings => experimental feature of ledger live.
Then you will see the app.

Nevertheless, issue remains on my side.
I went to polkadot-js and i follow those steps:

- Switched to on the "only for this network" radiobox on my polkadot account that is managed by my Ledger
- Went to Kusama network and removed all accounts, just in case.
- Launch the kusama_sec on my ledger
- Import account from my Ledger

And then yes an account appeared, but it's empty. **My KSM are not there**.
This app generated yet another account with another public address.
But it's still not the good one.

I have no idea how this thing got tested or even if there is only one potential issue regarding interactions between polkadot-js and Ledger.........

**Pull request closed without merging**
